name: CI/CD Pipeline
# teste
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout codigo
      uses: actions/checkout@v4
      
    - name: configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: executar testes Maven
      run: mvn test
      
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: checkout codigo
      uses: actions/checkout@v4
      
    - name: configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: build projeto e .jar
      run: mvn clean package -DskipTests
      
    - name: upload artefato .jar
      uses: actions/upload-artifact@v4
      with:
        name: todo-api-jar
        path: target/*.jar
        retention-days: 30